# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 174)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 361, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.path.setBaseSize(QtCore.QSize(276, 20))
        self.path.setObjectName("path")
        self.horizontalLayout.addWidget(self.path)
        self.folder = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.folder.setObjectName("folder")
        self.horizontalLayout.addWidget(self.folder)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.url = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.url.setEnabled(True)
        self.url.setChecked(True)
        self.url.setObjectName("url")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.url)
        self.horizontalLayout_2.addWidget(self.url)
        self.file = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.file.setObjectName("file")
        self.buttonGroup.addButton(self.file)
        self.horizontalLayout_2.addWidget(self.file)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.send = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.send.setChecked(True)
        self.send.setObjectName("send")
        self.horizontalLayout_3.addWidget(self.send)
        self.clean = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.clean.setObjectName("clean")
        self.horizontalLayout_3.addWidget(self.clean)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.go_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.go_button.setBaseSize(QtCore.QSize(359, 23))
        self.go_button.setObjectName("go_button")
        self.gridLayout_2.addWidget(self.go_button, 3, 0, 1, 1)
        self.gridLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuDick = QtWidgets.QMenu(self.menuBar)
        self.menuDick.setObjectName("menuDick")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuDick.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "web2kindle bastard"))
        self.folder.setText(_translate("MainWindow", "..."))
        self.url.setText(_translate("MainWindow", "url"))
        self.file.setText(_translate("MainWindow", "file"))
        self.send.setText(_translate("MainWindow", "send"))
        self.clean.setText(_translate("MainWindow", "clean"))
        self.go_button.setText(_translate("MainWindow", "Go motherfucker!"))
        self.menuDick.setTitle(_translate("MainWindow", "dick"))

